config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      resources :links, only: [:update, :destroy]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, presence: true, url: true
  validates :title, presence: true
  enum read: [:false, :true]
  belongs_to :user
  has_many :link_tags, dependent: :destroy
  has_many :tags, through: :link_tags

  def opposite_read_value
    read == 'true' ? 'false' : 'true'
  end

  def tag_names
    tags.pluck(:name).join(', ')
  end
end

app/models/link_tag.rb
class LinkTag < ApplicationRecord
  belongs_to :link
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :link_tags
  has_many :links, through: :link_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :links
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  before_action :set_link

  def update
    @link.update_attributes(read: @link.opposite_read_value)
    render json: @link
  end

  def destroy
    @link.destroy
    render json: @link
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:edit, :update]

  def index
    redirect_to login_path and return if !current_user
    @links = Link.where(user: current_user)
  end

  def create
    @link = Link.new(parsed_link_params)
    if @link.save
      flash[:success] = "Link to #{@link.title} successfully added."
      redirect_to links_path
    else
      flash[:danger] = @link.errors.full_messages.join(', ')
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @link.update(parsed_link_params)
      flash[:success] = "Link updated successfully."
      redirect_to links_path
    else
      flash.now[:danger] = @link.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :user_id, :tags)
  end

  def set_link
    @link = Link.find(params[:id])
  end

  def parsed_link_params
    clean_params = link_params
    clean_params[:tags] = stripped(clean_params[:tags])
    clean_params
  end

  def stripped(words)
    separated = words.downcase.split(',')
    separated.map { |word| Tag.find_or_create_by(name: word.strip) }
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to links_path if current_user
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Successfully logged in. Welcome, #{@user.email}!"
      redirect_to links_path
    else
      flash.now[:danger] = "Login information incorrect."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :process_password_mismatch, only: [:create]

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account created. Welcome, #{@user.email}!"
      redirect_to links_path
    else
      flash[:danger] = @user.errors.full_messages.join(', ')
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def process_password_mismatch
    if params[:user][:password] != params[:user][:verify_password]
      flash[:danger] = 'Passwords must match. Please try again.'
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def status(link)
    link.read == 'true' ? 'Unread' : 'Read'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URLockbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= sanitize(value) %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/edit.html.erb
<h1>Edit <%= @link.title %></h1>
<%= render partial: 'shared/link_form', locals: { target: @link, path: link_path(@link), button: "Update"} %>

app/views/links/index.html.erb
<div class="col-md-12 header">
  <h1 class="col-md-11">Add a New Link</h1>
  <%= link_to "Sign Out", logout_path, method: :delete, class: 'btn btn-primary col-md-1 sign-out' %>
</div>

<%= render partial: 'shared/link_form', locals: { target: :link, path: links_path, button: "Submit"} %>

<% if @links.count > 0 %>
  <center>
    <div class="form-group" id="link-search-box">
      <label for="search-box">Search</label>
      <input type="text" class="form-control" id="search-box" placeholder="Search for a link...">
    </div>
    <div>
      <button class="btn btn-default filter" type="button" name="filter-read">Filter Read</button>
      <button class="btn btn-default filter" type="button" name="filter-unread">Filter Unread</button>
      <button class="btn btn-default filter" type="button" name="filter-all">Show All</button>
      <button class="btn btn-default filter" type="button" name="sort-alphabetically">Sort All A-Z</button>
    </div>
  </center>
  <h1>Your Links</h1>
  <table class="table table-responsive table-bordered table-striped" id="links">
    <thead>
      <th>Title</th>
      <th>URL</th>
      <th>Tags</th>
      <th>Status</th>
      <th>Modify</th>
    </thead>
    <tbody class='link-table-body'>
      <% @links.each do |link| %>
        <tr id="<%= link.id %>" class="link" data-all="<%= link.title %> <%= link.url %> <%= link.tag_names %>">
          <td class="read-<%= link.read %> affected-by-read"><%= link.title %></td>
          <td class="read-<%= link.read %> affected-by-read"><%= link_to link.url, link.url %></td>
          <td class="tags">
            <% if link.tags %>
              <% link.tags.each do |tag| %>
                <button class="btn btn-info btn-xs" type="button"><%= tag.name %></button>
              <% end %>
            <% end %>
          </td>
          <td class="status"><%= link_to "Mark as #{status(link)}", '#' %></td>
          <td>
            <%= link_to "Edit", edit_link_path(link), class: "btn btn-xs btn-warning" %>
            <button class="btn btn-xs btn-danger delete" type="button">Delete</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/shared/_link_form.html.erb
<div class="well" id="link-form">
  <%= form_for(target, url: path) do |f| %>
    <div class="form-group">
      <%= f.label :url, "URL" %>
      <%= f.url_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :tags, "Tags (separate multiple with a comma - Example: 'search, fun, hello')" %>
      <%= f.text_field :tags, class: "form-control", value: target.is_a?(Link) ? target.tag_names : '' %>
    </div>

    <%= f.hidden_field :user_id, { value: current_user.id }%>
    <%= f.submit button, class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/new.html.erb
<center><h1>Sign Up</h1></center>
<div class="well" id="login-form">
  <%= form_for(:user, url: users_path) do |f| %>
    <div class="form-group">
      <%= f.label :email, "E-mail" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :verify_password, "Verify Password" %>
      <%= f.password_field :verify_password, class: "form-control" %>
    </div>

    <%= f.submit "Sign Up", class: "btn btn-default" %>
  <% end %>
</div>